// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'store.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1841108333;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'core_crypto',
        ioDirectory: '../core_crypto/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiVaultHandleChangePassword({
    required VaultHandle that,
    required String old,
    required String new_,
  });

  Future<VaultHandle> crateApiVaultHandleCreate({
    required String path,
    required String password,
  });

  Future<String> crateApiVaultHandleDeviceId({required VaultHandle that});

  Future<EntryDraft> crateApiVaultHandleGetFull({
    required VaultHandle that,
    required String id,
  });

  Future<List<EntryMeta>> crateApiVaultHandleListMeta({
    required VaultHandle that,
  });

  Future<List<EntryMeta>> crateApiVaultHandleListTrash({
    required VaultHandle that,
  });

  Future<void> crateApiVaultHandleRestore({
    required VaultHandle that,
    required String id,
  });

  Future<String> crateApiVaultHandleRevealPassword({
    required VaultHandle that,
    required String id,
  });

  Future<void> crateApiVaultHandleSoftDelete({
    required VaultHandle that,
    required String id,
  });

  Future<VaultHandle> crateApiVaultHandleUnlock({
    required String path,
    required String password,
  });

  Future<EntryMeta> crateApiVaultHandleUpsert({
    required VaultHandle that,
    required EntryDraft draft,
  });

  String crateApiPing();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VaultHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VaultHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VaultHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiVaultHandleChangePassword({
    required VaultHandle that,
    required String old,
    required String new_,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            that,
            serializer,
          );
          sse_encode_String(old, serializer);
          sse_encode_String(new_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultHandleChangePasswordConstMeta,
        argValues: [that, old, new_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultHandleChangePasswordConstMeta =>
      const TaskConstMeta(
        debugName: "VaultHandle_change_password",
        argNames: ["that", "old", "new_"],
      );

  @override
  Future<VaultHandle> crateApiVaultHandleCreate({
    required String path,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultHandleCreateConstMeta,
        argValues: [path, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultHandleCreateConstMeta => const TaskConstMeta(
    debugName: "VaultHandle_create",
    argNames: ["path", "password"],
  );

  @override
  Future<String> crateApiVaultHandleDeviceId({required VaultHandle that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultHandleDeviceIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultHandleDeviceIdConstMeta =>
      const TaskConstMeta(
        debugName: "VaultHandle_device_id",
        argNames: ["that"],
      );

  @override
  Future<EntryDraft> crateApiVaultHandleGetFull({
    required VaultHandle that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_draft,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultHandleGetFullConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultHandleGetFullConstMeta => const TaskConstMeta(
    debugName: "VaultHandle_get_full",
    argNames: ["that", "id"],
  );

  @override
  Future<List<EntryMeta>> crateApiVaultHandleListMeta({
    required VaultHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_entry_meta,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultHandleListMetaConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultHandleListMetaConstMeta =>
      const TaskConstMeta(
        debugName: "VaultHandle_list_meta",
        argNames: ["that"],
      );

  @override
  Future<List<EntryMeta>> crateApiVaultHandleListTrash({
    required VaultHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_entry_meta,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultHandleListTrashConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultHandleListTrashConstMeta =>
      const TaskConstMeta(
        debugName: "VaultHandle_list_trash",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiVaultHandleRestore({
    required VaultHandle that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultHandleRestoreConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultHandleRestoreConstMeta => const TaskConstMeta(
    debugName: "VaultHandle_restore",
    argNames: ["that", "id"],
  );

  @override
  Future<String> crateApiVaultHandleRevealPassword({
    required VaultHandle that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultHandleRevealPasswordConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultHandleRevealPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "VaultHandle_reveal_password",
        argNames: ["that", "id"],
      );

  @override
  Future<void> crateApiVaultHandleSoftDelete({
    required VaultHandle that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultHandleSoftDeleteConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultHandleSoftDeleteConstMeta =>
      const TaskConstMeta(
        debugName: "VaultHandle_soft_delete",
        argNames: ["that", "id"],
      );

  @override
  Future<VaultHandle> crateApiVaultHandleUnlock({
    required String path,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultHandleUnlockConstMeta,
        argValues: [path, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultHandleUnlockConstMeta => const TaskConstMeta(
    debugName: "VaultHandle_unlock",
    argNames: ["path", "password"],
  );

  @override
  Future<EntryMeta> crateApiVaultHandleUpsert({
    required VaultHandle that,
    required EntryDraft draft,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            that,
            serializer,
          );
          sse_encode_box_autoadd_entry_draft(draft, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_meta,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultHandleUpsertConstMeta,
        argValues: [that, draft],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultHandleUpsertConstMeta => const TaskConstMeta(
    debugName: "VaultHandle_upsert",
    argNames: ["that", "draft"],
  );

  @override
  String crateApiPing() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPingConstMeta =>
      const TaskConstMeta(debugName: "ping", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VaultHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VaultHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle;

  @protected
  VaultHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VaultHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VaultHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EntryDraft dco_decode_box_autoadd_entry_draft(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_entry_draft(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  EntryDraft dco_decode_entry_draft(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return EntryDraft(
      id: dco_decode_opt_String(arr[0]),
      title: dco_decode_String(arr[1]),
      username: dco_decode_String(arr[2]),
      password: dco_decode_String(arr[3]),
      url: dco_decode_String(arr[4]),
      notes: dco_decode_String(arr[5]),
      totpUri: dco_decode_opt_String(arr[6]),
      tags: dco_decode_list_String(arr[7]),
      favorite: dco_decode_bool(arr[8]),
    );
  }

  @protected
  EntryMeta dco_decode_entry_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return EntryMeta(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      username: dco_decode_String(arr[2]),
      url: dco_decode_String(arr[3]),
      tags: dco_decode_list_String(arr[4]),
      favorite: dco_decode_bool(arr[5]),
      hasTotp: dco_decode_bool(arr[6]),
      createdAt: dco_decode_i_64(arr[7]),
      updatedAt: dco_decode_i_64(arr[8]),
      deletedAt: dco_decode_opt_box_autoadd_i_64(arr[9]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<EntryMeta> dco_decode_list_entry_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_entry_meta).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VaultHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VaultHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VaultHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EntryDraft sse_decode_box_autoadd_entry_draft(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_entry_draft(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  EntryDraft sse_decode_entry_draft(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_notes = sse_decode_String(deserializer);
    var var_totpUri = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_favorite = sse_decode_bool(deserializer);
    return EntryDraft(
      id: var_id,
      title: var_title,
      username: var_username,
      password: var_password,
      url: var_url,
      notes: var_notes,
      totpUri: var_totpUri,
      tags: var_tags,
      favorite: var_favorite,
    );
  }

  @protected
  EntryMeta sse_decode_entry_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_favorite = sse_decode_bool(deserializer);
    var var_hasTotp = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_deletedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    return EntryMeta(
      id: var_id,
      title: var_title,
      username: var_username,
      url: var_url,
      tags: var_tags,
      favorite: var_favorite,
      hasTotp: var_hasTotp,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      deletedAt: var_deletedAt,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<EntryMeta> sse_decode_list_entry_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EntryMeta>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_entry_meta(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
    VaultHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
    VaultHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
    VaultHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_entry_draft(
    EntryDraft self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_entry_draft(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_entry_draft(EntryDraft self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.notes, serializer);
    sse_encode_opt_String(self.totpUri, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_bool(self.favorite, serializer);
  }

  @protected
  void sse_encode_entry_meta(EntryMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_bool(self.favorite, serializer);
    sse_encode_bool(self.hasTotp, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.deletedAt, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_entry_meta(
    List<EntryMeta> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_entry_meta(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class VaultHandleImpl extends RustOpaque implements VaultHandle {
  // Not to be used by end users
  VaultHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VaultHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_VaultHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_VaultHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_VaultHandlePtr,
  );

  /// 改主密码（新盐 + 新 KEK 重包裹同一 DEK）。
  Future<void> changePassword({required String old, required String new_}) =>
      RustLib.instance.api.crateApiVaultHandleChangePassword(
        that: this,
        old: old,
        new_: new_,
      );

  /// 本设备 id（rev 前缀）。
  Future<String> deviceId() =>
      RustLib.instance.api.crateApiVaultHandleDeviceId(that: this);

  /// 完整明文（编辑页用）。
  Future<EntryDraft> getFull({required String id}) =>
      RustLib.instance.api.crateApiVaultHandleGetFull(that: this, id: id);

  /// 未删除条目元数据（永不含密码/备注/TOTP secret）。
  Future<List<EntryMeta>> listMeta() =>
      RustLib.instance.api.crateApiVaultHandleListMeta(that: this);

  /// 回收站条目元数据。
  Future<List<EntryMeta>> listTrash() =>
      RustLib.instance.api.crateApiVaultHandleListTrash(that: this);

  /// 从回收站恢复。
  Future<void> restore({required String id}) =>
      RustLib.instance.api.crateApiVaultHandleRestore(that: this, id: id);

  /// 单条按需解密密码（"点击显示"；调用方负责 10s 内丢弃返回串）。
  Future<String> revealPassword({required String id}) => RustLib.instance.api
      .crateApiVaultHandleRevealPassword(that: this, id: id);

  /// 软删除（写墓碑）。
  Future<void> softDelete({required String id}) =>
      RustLib.instance.api.crateApiVaultHandleSoftDelete(that: this, id: id);

  /// 新建或整体更新条目，返回更新后的元数据。
  Future<EntryMeta> upsert({required EntryDraft draft}) =>
      RustLib.instance.api.crateApiVaultHandleUpsert(that: this, draft: draft);
}
