// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 条目元数据（永不含密码/备注/TOTP secret）。
class EntryMeta {
  final String id;
  final String title;
  final String username;
  final String url;
  final List<String> tags;
  final bool favorite;
  final bool hasTotp;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;

  const EntryMeta({
    required this.id,
    required this.title,
    required this.username,
    required this.url,
    required this.tags,
    required this.favorite,
    required this.hasTotp,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      username.hashCode ^
      url.hashCode ^
      tags.hashCode ^
      favorite.hashCode ^
      hasTotp.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryMeta &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          username == other.username &&
          url == other.url &&
          tags == other.tags &&
          favorite == other.favorite &&
          hasTotp == other.hasTotp &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt;
}
